#spring:
#
#  application:
#    name: blog
#
#  mybatis:
#    base-package: com.deway.blog.mapper
#    mapper-locations: classpath:/mapper/*Mapper.xml
#    type-aliases-package: com.deway.blog.entity
#
#---
#spring:
#
#  profile: company
#
#  datasource:
#    user:
#      username: wcdmaria
#      password: wistron888
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://10.62.201.102:3306/buck
#
#    blog:
#      username: wcdmaria
#      password: wistron888
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://10.62.201.102:3306/buck2
#
#    redis:
#      host: 127.0.0.1
#      port: 6379
#---
#spring:
#
#  profile: home
#
#  datasource:
#    user:
#      username: root
#      password: 2012dwDW
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://www.touchim.cn:3306/auth
#
#    blog:
#      username: root
#      password: 2012dwDW
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://www.touchim.cn:3306/blog
#
#  redis:
#    host: www.touchim.cn
#    port: 6379

spring:

  application:
    name: blog

  datasource:
    user:
      username: root
      password: 2012dwDW
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://www.touchim.cn/auth

    blog:
      username: root
      password: 2012dwDW
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://www.touchim.cn/blog

  auth:
    session-expire: 3000 # 单位秒
    authorization: true
    multi-sign-on: false # @todo 建议false，多点登录我还没想到好的解决方案 考虑文件系统的索引结点方案

  upload:
    path: F:/Idea Project/upload/ #空格路径，程序一旦正式运行就不要改
    max-per-file: 3145728
    allowed-type:
      - jpeg
      - png
      - bmp
      - jpg

  redis:
    host: www.touchim.cn
    port: 6379