spring:

  application:
    name: blog

  datasource:
      user:
        username: wcdmaria
        password: wistron888
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://10.62.201.102:3306/buck
      blog:
        username: wcdmaria
        password: wistron888
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://10.62.201.102:3306/buck2

  redis:
    host:
    port: